trigger:
- main

pool:
  name: fernando-laptop

stages:
- stage: BuildAndPush
  displayName: Build and Push stage
  jobs:  
  - job: BuildAndPush
    displayName: Build and push job
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: fraou022/final-group-project
        dockerfile: '**/Project/Dockerfile'
        containerRegistry: 'docker-hub'
        tags: 'latest'

    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'manifests'
        path: 'manifests'