# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: fernando-laptop
    steps:
    - task: Docker@2
      inputs:
        repository: 'fraou022/final-group-project'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'