trigger:
- staging

pool:
  name: fernando-laptop

stages:
- stage: BuildAndPush
  displayName: Build and Push stage
  jobs:  
  - job: BuildAndPush
    displayName: Build and push job
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: fraou022/gng5300-group1-project
        dockerfile: '**/Project/Dockerfile'
        containerRegistry: 'docker-hub-fraou022'
        tags: 'stg'

    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'manifests-stg'
        path: 'manifests'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: BuildAndPush
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    environment: 'STG.stg' #customize with your environment
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'manifests-stg'
              downloadPath: '$(System.ArtifactsDirectory)/manifests'

          - task: Kubernetes@1
            displayName: 'Apply STG Manifest'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'GNG5300_Group1_Project_ResourceGroup'
              azureResourceGroup: 'GNG5300_Group1_Project'
              kubernetesCluster: 'GNG5300_Group1_Project_Cluster'
              namespace: 'stg'
              command: 'apply'
              arguments: '-f $(System.ArtifactsDirectory)/manifests/deployment.yml'
          
          - task: Kubernetes@1
            displayName: 'Restart Deployment'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'GNG5300_Group1_Project_ResourceGroup'
              azureResourceGroup: 'GNG5300_Group1_Project'
              kubernetesCluster: 'GNG5300_Group1_Project_Cluster'
              namespace: 'stg'
              command: 'rollout'
              arguments: 'restart deployment gng5300-group1-project-stg'


          #- task: KubernetesManifest@1
          #  inputs:
          #    action: 'deploy'
          #    connectionType: 'azureResourceManager'
          #    azureSubscriptionConnection: 'GNG5300_Group1_Project_ResourceGroup'
          #    azureResourceGroup: 'GNG5300_Group1_Project'
          #    kubernetesCluster: 'GNG5300_Group1_Project_Cluster'
          #    namespace: 'dev'
          #    manifests: '$(System.ArtifactsDirectory)/manifests/*.yml'
          #    containers: 'fraou022/gng5300-group1-project:dev'