trigger:
- main

pool:
  name: fernando-laptop

jobs:
- job: BuildDockerImage
  displayName: 'Build Docker Image'
  steps:
  - checkout: self
  - task: Docker@2
    inputs:
      containerRegistry: 'yourAzureContainerRegistryServiceConnection'  # Replace with your Azure Container Registry service connection
      repository: 'youracr.azurecr.io/yourrepository'  # Replace with your Azure Container Registry and repository name
      command: 'build'
      Dockerfile: '**/Project/Dockerfile'
      tags: 'latest'

