trigger:
- main

pool:
  name: fernando-laptop

jobs:
- job: BuildAndPushDockerImage
  displayName: 'Build Docker Image'
  steps:
  - checkout: self
  - task: Docker@2
    inputs:
      containerRegistry: 'docker-hub'  # Replace with your Azure Container Registry service connection
      repository: 'fraou022/final-group-project'  # Replace with your Azure Container Registry and repository name
      command: 'build'
      Dockerfile: '**/Project/Dockerfile'
      tags: 'latest'
  - task: Docker@2
    inputs:
      containerRegistry: 'docker-hub'
      repository: 'fraou022/final-group-project'
      command: 'push'
      tags: 'latest'