trigger:
- development

pool:
  name: fernando-laptop

stages:
- stage: BuildAndPush
  displayName: Build and Push stage
  jobs:  
  - job: BuildAndPush
    displayName: Build and push job
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: fraou022/gng5300-group1-project
        dockerfile: '**/Project/Dockerfile'
        containerRegistry: 'docker-hub-fraou022'
        tags: 'dev'

    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'manifests-dev'
        path: 'manifests'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: BuildAndPush
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    environment: 'DEV.dev' #customize with your environment
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'manifests-dev'
              downloadPath: '$(System.ArtifactsDirectory)/manifests'

          - task: ReplaceTokens@5
            inputs:
              targetFiles: '$(System.ArtifactsDirectory)/manifests/*.yml'  # Specify the path to your YAML file
              encoding: 'auto'
              writeBOM: true
              tokenRegex: 'REPLACE_WITH_TIMESTAMP'
              newToken: '$(Build.SourceVersion)'

          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'GNG5300_Group1_Project_ResourceGroup'
              azureResourceGroup: 'GNG5300_Group1_Project'
              kubernetesCluster: 'GNG5300_Group1_Project_Cluster'
              namespace: 'dev'
              manifests: '$(System.ArtifactsDirectory)/manifests/*.yml'
              containers: 'fraou022/gng5300-group1-project:dev'