trigger:
- staging

pool:
  name: fernando-laptop

stages:
- stage: BuildAndPush
  displayName: Build and Push stage
  jobs:  
  - job: BuildAndPush
    displayName: Build and push job
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: fraou022/final-group-project
        dockerfile: '**/Project/Dockerfile'
        containerRegistry: 'docker-hub'
        tags: 'stg'

    - task: PublishPipelineArtifact@1
      inputs:
        artifactName: 'manifests-stg'
        path: 'manifests'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: BuildAndPush
  jobs:
  - deployment: Deploy
    displayName: Deploy job
    environment: 'STG.stg' #customize with your environment
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'manifests-stg'
              downloadPath: '$(System.ArtifactsDirectory)/manifests'

          - task: KubernetesManifest@1
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'GNG5300_Group1_Project_ResourceGroup'
              azureResourceGroup: 'GNG5300_Group1_Project'
              kubernetesCluster: 'GNG5300_Group1_Project_Cluster'
              namespace: 'stg'
              manifests: |
                manifests/service.yml 
                manifests/deployment.yml
              containers: 'fraou022/final-group-project:stg'