apiVersion: v1
kind: Service
metadata:
  name: gng5300-group1-project-prd-service
spec:
  selector:
    app: gng5300-group1-project-prd
  ports:
    - protocol: TCP
      port: 80  # Exposed port on the service
      targetPort: 5000  # Port your Flask app is running on inside the pods
  type: LoadBalancer  # or NodePort, ClusterIP based on your needs
